name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Grant execute permission for mvnw
      run: chmod +x mvnw

    - name: Build and Test
      run: |
        export SPRING_PROFILES_ACTIVE=test
        ./mvnw clean verify -B -Dspring.profiles.active=test
      env:
        MAVEN_OPTS: "-Dfile.encoding=UTF-8 -Dmaven.resources.encoding=UTF-8"
        SPRING_PROFILES_ACTIVE: test

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          target/surefire-reports/
          target/failsafe-reports/

    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: biblioteca-api
        path: target/*.jar