name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Grant execute permission for mvnw
      run: chmod +x mvnw

    - name: Build and Test
      run: ./mvnw clean package

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: biblioteca-api
        path: target/*.jar